HotelManagement/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotelManagement.Services;
using HotelManagement.ViewModel;

namespace HotelManagement.Controllers
{
    public class BookingController : Controller
    {
        // GET: Booking
        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                CustomerVM _objcustomerVMList = new CustomerVM();
                _objcustomerVMList.customerVMlist = new List<CustomerVM>();
                CustomerServices _objCustomerServices = new CustomerServices();

                _objcustomerVMList.customerVMlist = _objCustomerServices.GetBookingsList();

                return View(_objcustomerVMList);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]

        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpPost]
        public ActionResult Create(CustomerVM _objCustomerVM)
        {
            try
            {

                CustomerServices _objCustomerServices = new CustomerServices();
                _objCustomerServices.create(_objCustomerVM);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            try
            {
                CustomerVM _objcustomerVM = new CustomerVM();
                _objcustomerVM.customerVMlist = new List<CustomerVM>();

                EmployeeServices _objEmployeeServices = new EmployeeServices();

                _objcustomerVM = _objEmployeeServices.GetEmployeeById(Id);

                return View(_objcustomerVM);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpPost]

        public ActionResult Update(CustomerVM _objCustomerVM)
        {
            try
            {
                CustomerServices _objCostomerServices = new CustomerServices();
                _objCostomerServices.Update(_objCustomerVM);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

    }
}

HotelManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelManagement.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HotelManagement/Controllers/InformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotelManagement.ViewModel;
using HotelManagement.Services;

namespace HotelManagement.Controllers
{
    public class InformationController : Controller
    {
        // GET: Information
        [HttpGet]
        public ActionResult CustomerInfo()
        {
            try
            {
                CustomerServices _objcustomerServices = new CustomerServices();
                CustomerVM _objcustomerVM = new CustomerVM();
                _objcustomerVM.customerVMlist = new List<CustomerVM>();

                _objcustomerVM.customerVMlist = _objcustomerServices.GetCustomerList();


                return View(_objcustomerVM);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        } 

        [HttpGet]
        public ActionResult RoomInfo()
        {
            try
            {
                EmployeeServices _objEmployeeServices = new EmployeeServices();
                RoomVM _objRoomVM = new RoomVM();
                _objRoomVM.RoomVMlist = new List<RoomVM>();

                _objRoomVM.RoomVMlist = _objEmployeeServices.GetRoomList();


                return View(_objRoomVM);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        } 

        [HttpGet]
        public ActionResult EmployeeInfo()
        {
            try
            {

                EmployeeServices _objEmployeeServices = new EmployeeServices();
                EmpolyeeVM _objEmployeeVM = new EmpolyeeVM();
                _objEmployeeVM.EmpolyeeVMlist = new List<EmpolyeeVM>();

                _objEmployeeVM.EmpolyeeVMlist = _objEmployeeServices.GetEmployeeList();


                return View(_objEmployeeVM);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

HotelManagement/Views/Booking/Create.cshtml
@model HotelManagement.ViewModel.CustomerVM
@{
    ViewBag.Title = "Create";
}

<script>
    $(document).ready(function () {

    });

    function BacktoIndex() {
        window.location.href = '@Url.Action("Index","Booking")'
    }
</script>

<h2>Create Booking</h2>

@using (Html.BeginForm("Create", "Booking", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row col-md-12">
            <div style="padding:10px;">
                <button type="button" class="btn btn-warning" id="btnBack" onclick="return BacktoIndex();">
                    <i class="glyphicon glyphicon-chevron-left"></i> Back
                </button>
            </div>
            <div>
                @{Html.RenderPartial("_BookingForm");}
            </div>
            <div style="padding:10px;">
                <button type="submit" class="btn btn-success" id="btnSubmit">
                    <i class="glyphicon glyphicon-ok"></i> Submit
                </button>
            </div>
        </div>
    </div>
}

HotelManagement/Views/Booking/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

@model HotelManagement.ViewModel.CustomerVM
@{
    ViewBag.Title = "Create";
}

<script>
    $(document).ready(function () {

    });

    function BacktoIndex() {
        window.location.href = '@Url.Action("Index","Booking")'
    }
</script>

<h2>Create Booking</h2>

@using (Html.BeginForm("Update", "Booking", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row col-md-12">
            <div style="padding:10px;">
                <button type="button" class="btn btn-warning" id="btnBack" onclick="return BacktoIndex();">
                    <i class="glyphicon glyphicon-chevron-left"></i> Back
                </button>
            </div>
            <div>
                @{Html.RenderPartial("_BookingForm");}
            </div>
            <div style="padding:10px;">
                <button type="submit" class="btn btn-success" id="btnSubmit">
                    <i class="glyphicon glyphicon-ok"></i> Submit
                </button>
            </div>
        </div>
    </div>
}

HotelManagement/Views/Booking/Index.cshtml
@model HotelManagement.ViewModel.CustomerVM
@{
    ViewBag.Title = "Index";
}


<style>
    .padCont {
        padding: 10px;
        padding-right: 20px;
    }
</style>
<script>
 $(document).ready(function () {
     $('.editBtn').click(function () {

         var Id = parseInt($(this).attr('id'))
         console.log(Id);
         window.location.href = '@Url.Action("Edit", "Booking")' + '/' + Id;
     });

 });
</script>

            <div class="container">

                <div class="form-horizontal">
                    <div class="row page-header">
                        <h2>Booking List</h2>
                        <div>
                            <button class="btn btn-primary padCont" type="button" onclick="window.location.href = '@Url.Action("Create", "Booking")'">
                                <i class="glyphicon glyphicon-plus"></i> New Booking
                            </button>
                            <button class="btn btn-primary padCont" type="button" onclick="window.location.href = '@Url.Action("CustomerInfo", "Information")'">Costomer Inforamtion</button>
                            <button class="btn btn-primary padCont" type="button" onclick="window.location.href = '@Url.Action("RoomInfo", "Information")'">Room information</button>
                            <button class="btn btn-primary padCont" type="button" onclick="window.location.href = '@Url.Action("EmployeeInfo", "Information")'">Employees information</button>
                        </div>
                    </div>
                    <div class="row">
                        <div id="Emptable">
                            <table class="table table-hover table-condensed table-striped">
                                <thead>
                                    <tr>
                                        <th>BookingId</th>
                                        <th>Name</th>
                                        <th>Address</th>
                                        <th>Email</th>
                                        <th>Mobile</th>
                                        <th>Gender</th>
                                        <th>RoomNumber</th>
                                        <th>CheckIn Date</th>
                                        <th>CheckOut Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        if (Model.customerVMlist != null)
                                        {
                                            foreach (var item in Model.customerVMlist)
                                            {
                                                <tr>
                                                    <td>@item.Bookingvm.Id</td>
                                                    <td>@item.Name</td>
                                                    <td>@item.Address</td>
                                                    <td>@item.Email</td>
                                                    <td>@item.Mobile</td>
                                                    <td>@item.Gender</td>
                                                    <td>@item.Bookingvm.Roomnumber</td>
                                                    <td>@item.Bookingvm.CheckIn</td>
                                                    <td>@item.Bookingvm.CheckOut</td>

                                                    <td>
                                                        <span class="btn btn-info padCont editBtn" id="@item.Bookingvm.Id"><i class="glyphicon glyphicon-edit"></i> CheckOut</span>

                                                    </td>
                                                </tr>
                                            }
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>

HotelManagement/Views/Booking/_BookingForm.cshtml
@model HotelManagement.ViewModel.CustomerVM

<style>
    .row {
        padding: 10px
    }
</style>
<script>
    $(document).ready(function () {
        
        $('#Bookingvm_Action').click(function () {
            var date = new Date();
            var day = date.getDate();
            var Month = date.getMonth();
            var year = date.getFullYear();
            var curr_hour = date.getHours();
            var curr_min = date.getMinutes();
            var curr_sec = date.getSeconds();
            if (day < 10) {
                day = "0" + day;
            }
            if (Month < 10) {
                Month = "0" + Month;
            }
            if (curr_hour < 10) {
                curr_hour = "0" + curr_hour;
            }
            if (curr_min < 10) {
                curr_min = "0" + curr_min;
            }
            if (curr_sec < 10) {
                curr_sec = "0" + curr_sec;
            }
            if ($("#Bookingvm_Action").prop('checked') == true) {
                $("#CheckIN").val(year + "-" + Month + "-" + day + " " + curr_hour + ":" + curr_min + ":" + curr_sec );
            }
            else {
                console.log(2);
                $("#checkOUT").val(year + "-" + Month + "-" + day + " " + curr_hour + ":" + curr_min + ":" + curr_sec );
            }
            
        });

        //var act = $("#Action").val()

        //if (act == true)
        //    $("#CheckIN").val(new Date())
        //else
        //    $("#CheckOUI").val(new Date())
    });
</script>

<div class="form-horizontal">
    <div class="col-md-12">
        @Html.HiddenFor(model => model.Bookingvm.Id)
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Name)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control reset", @id = "CustomerName" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Mobile)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control reset", @id = "Mobile" } })
                    @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Gender)
                </div>
                <div class="col-md-8">
                    <select class="form-control" id="Gender" name="Gender">
                        <option>Select Gender</option>
                        <option>Male</option>
                        <option>Female</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Address)
                    </div>
                    <div class="col-md-8">
                        @Html.TextAreaFor(model => model.Address, new { htmlAttributes = new { @class = "form-control reset", @id = "Address" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div> 
            <div class="row">
                <div class="col-md-6">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Images)
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Images, new { type = "file",htmlAttributes = new { @class = "form-control", @id = "Image" } })
                        @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div> 
            <div class="row">
                <div class="col-md-6">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Email)
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control reset", @id = "txtLastName" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div> 
            <div class="row">
                <div class="col-md-6">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Bookingvm.Roomnumber)
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Bookingvm.Roomnumber, new { htmlAttributes = new { @class = "form-control reset", @id = "txtLastName" } })
                        @Html.ValidationMessageFor(model => model.Bookingvm.Roomnumber, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div> 
            <div class="row">
                <div class="col-md-6">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Bookingvm.Action)
                    </div>
                    <div class="col-md-8">
                       @Html.CheckBoxFor(model => model.Bookingvm.Action, new { htmlAttributes = new { @class = "form-control reset", @id = "Action"  } })
                    </div>
                </div>
            </div> 
            <div class="row">
                <div class="col-md-6">
                    <div class="col-md-4">
                      @Html.EditorFor(model => model.Bookingvm.CheckIn, new { htmlAttributes = new { @class = "form-control reset", @id = "CheckIN" } })
                    </div>
                    <div class="col-md-4">
                      @Html.EditorFor(model => model.Bookingvm.CheckOut, new { htmlAttributes = new { @class = "form-control reset", @id = "checkOUT" } })
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>

HotelManagement/Views/Booking/update.cshtml
@model HotelManagement.ViewModel.CustomerVM
@{
    ViewBag.Title = "update";
}


<script>
    $(document).ready(function () {

    });

    function BacktoIndex() {
        window.location.href = '@Url.Action("Index","Employee")'
    }
</script>

<h2>Update Booking</h2>

@using (Html.BeginForm("Create", "Employee", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row col-md-12">
            <div style="padding:10px;">
                <button type="button" class="btn btn-warning" id="btnBack" onclick="return BacktoIndex();">
                    <i class="glyphicon glyphicon-chevron-left"></i> Back
                </button>
            </div>
            <div>
                @{Html.RenderPartial("_BookingForm");}
            </div>
            <div style="padding:10px;">
                <button type="submit" class="btn btn-success" id="btnSubmit">
                    <i class="glyphicon glyphicon-ok"></i> Submit
                </button>
            </div>
        </div>
    </div>
}

HotelManagement/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HotelManagement/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HotelManagement/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HotelManagement/Views/Information/CustomerInfo.cshtml
@model HotelManagement.ViewModel.CustomerVM
@{
    ViewBag.Title = "CustomerInfo";
}

<h2>CustomerInfo</h2>



<script>
    $(document).ready(function () {

    });

    function BacktoIndex() {
        window.location.href = '@Url.Action("Index","Booking")'
    }
</script>
<style>
    .padCont {
        padding: 10px;
        padding-right: 20px;
    }
</style>


<div class="container">

    <div class="form-horizontal">
        <div class="row page-header">
            <h2>Customers List</h2>
            <div>
                <button type="button" class="btn btn-warning" id="btnBack" onclick="return BacktoIndex();">
                    <i class="glyphicon glyphicon-chevron-left"></i> Back
                </button>
            </div>
        </div>
        <div class="row">
            <div id="Emptable">
                <table class="table table-hover table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>CustomerId</th>
                            <th>Name</th>
                            <th>Address</th>
                            <th>Email</th>
                            <th>Mobile</th>
                            <th>Gender</th>
                            <th>Images</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model.customerVMlist != null)
                            {
                                foreach (var item in Model.customerVMlist)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Name</td>
                                        <td>@item.Address</td>
                                        <td>@item.Email</td>
                                        <td>@item.Mobile</td>
                                        <td>@item.Gender</td>
                                        <td>@item.Images</td>
                                    </tr>
                                }
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

HotelManagement/Views/Information/EmployeeInfo.cshtml
@model HotelManagement.ViewModel.EmpolyeeVM
@{
    ViewBag.Title = "EmployeeInfo";
}

<h2>EmployeeInfo</h2>



<script>
    $(document).ready(function () {

    });

    function BacktoIndex() {
        window.location.href = '@Url.Action("Index","Booking")'
    }
</script>

<style>
    .padCont {
        padding: 10px;
        padding-right: 20px;
    }
</style>


<div class="container">

    <div class="form-horizontal">
        <div class="row page-header">
            <div>
                <button type="button" class="btn btn-warning" id="btnBack" onclick="return BacktoIndex();">
                    <i class="glyphicon glyphicon-chevron-left"></i> Back
                </button>
            </div>
        </div>
        <div class="row">
            <div id="Emptable">
                <table class="table table-hover table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>EmployeeId</th>
                            <th>Name</th>
                            <th>Password</th>
                            <th>Age</th>
                            <th>Gender</th>
                            <th>Address</th>
                            <th>Images</th>
                            <th>Email</th>
                            <th>JobType</th>
                            <th>Salary</th>
                            <th>ShiftTime</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model.EmpolyeeVMlist != null)
                            {
                                foreach (var item in Model.EmpolyeeVMlist)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Name</td>
                                        <td>@item.Password</td>
                                        <td>@item.Age</td>
                                        <td>@item.Gender</td>
                                        <td>@item.Address</td>
                                        <td>@item.Images</td>
                                        <td>@item.Email</td>
                                        <td>@item.Jobtype</td>
                                        <td>@item.Salary</td>
                                        <td>@item.ShiftTime</td>

                                    </tr>
                                }
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

HotelManagement/Views/Information/RoomInfo.cshtml
@model HotelManagement.ViewModel.RoomVM
@{
    ViewBag.Title = "RoomInfo";
}

<h2>RoomInfo</h2>



<script>
    $(document).ready(function () {

    });

    function BacktoIndex() {
        window.location.href = '@Url.Action("Index","Booking")'
    }
</script>
<style>
    .padCont {
        padding: 10px;
        padding-right: 20px;
    }
</style>

<div class="container">

    <div class="form-horizontal">
        <div class="row page-header">
            <div>
                <button type="button" class="btn btn-warning" id="btnBack" onclick="return BacktoIndex();">
                    <i class="glyphicon glyphicon-chevron-left"></i> Back
                </button>
            </div>
        </div>
        <div class="row">
            <div id="Emptable">
                <table class="table table-hover table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>RoomId</th>
                            <th>Roomnumber</th>
                            <th>Description</th>
                            <th>DayCharge</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if (Model.RoomVMlist != null)
                            {
                                foreach (var item in Model.RoomVMlist)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Roomnumber</td>
                                        <td>@item.Description</td>
                                        <td>@item.DayCharge</td>
                                        <td>@item.status</td>
                                    </tr>
                                }
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

HotelManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Bookings", "Index", "Booking")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>